services:
  wolwm:
    build: .
    container_name: wolwm
    network_mode: "host"
    restart: "unless-stopped"
    command: "--host 0.0.0.0"
    volumes:
      - ./wolwm_data:/wolwm
    environment:
      - WOLWM_DATA_FOLDER=/wolwm
