version: "3"

tasks:
  install_backend:
    cmds:
      - poetry -C backend install
    sources:
      - backend/wolwm/**/*.py

  backend:
    deps: [install_backend]
    cmds:
      - poetry -C backend run wolwm -dev -v
